config/routes.rb
Rails.application.routes.draw do	
	
	post 'bank_accounts/add_operation'
	get 'bank_accounts/delete_operation'
	
	post 'bank_accounts/define_date'
	
	post 'bank_accounts/update_operation'
	
	post 'operation_classifications/edit'
	post 'operation_classifications/update'
	post 'operation_classifications/add_operation_classification'
	
	get 'operations/check'
	get 'operations/uncheck'
	
	resources 	:bank_accounts, 
				:operations, 
				:users, 
				:operation_classifications,
				:transfers
	
	get 'home/login'
	post 'home/login'
	get 'home/index'
	get 'home/logout'

	get 'users/new'
	post 'users/create'
	
	get 'stats/evolution_solde'
	post 'stats/evolution_solde_data'
	get 'stats/operation_distribution'
	post 'stats/operation_distribution_data'
	get '/stats/evolution_poste'
	post '/stats/evolution_poste_data'
	post '/stats/input_output_data'
	
	

  root 'home#login'

end

app/models/operation_classification.rb
class OperationClassification < ActiveRecord::Base
	has_many :operations
	has_many :transfers
	belongs_to :user
	
	validates 	:wording, 
				presence: { message: "Le libellé est obligatoire" }
end

app/controllers/operation_classifications_controller.rb
class OperationClassificationsController < ApplicationController

	before_filter :check_if_logged

	def index
		@oc = OperationClassification.new
		@operationClassifications = OperationClassification.where(user_id: session[:current_user_id])
	end

	def edit
		@oc = OperationClassification.find(params[:id])		
	end
	
	def update
		#render plain: params.inspect
		@oc = OperationClassification.find(params[:id])
		if(@oc.update(wording: params[:operation_classification][:wording]))			
			redirect_to action: 'index'
		else
			render 'edit'
		end
	end
	
	def destroy
		@oc = OperationClassification.find(params[:id])
		@oc.destroy		
		redirect_to action: 'index'	
	end
	
	def add_operation_classification
		#render plain: params.inspect	
		@oc = OperationClassification.new(wording: params[:operation_classification][:wording], user_id: session[:current_user_id])
		if(@oc.valid?)
			@oc.save
			redirect_to action: 'index'	
		else	
			@operationClassifications = OperationClassification.where(user_id: session[:current_user_id])
			render 'index'
		end

	end
end

app/views/operation_classifications/edit.html.erb
<% content_for :jumbo do %>
	<h1 class="page-header">Libellé du poste</h1>
<% end %>

<div class="row">

	<%= render partial: "layouts/error", locals: {errors: @oc.errors} %>

	<%= form_for @oc , html: {:class => "form-horizontal"} do |u| %>
		
		<div class="form-group">		
			<%= label "wording", "Libellé", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= u.text_field( :wording, class: "form-control", placeholder: "Libellé", required: true )%>
			</div>	
		</div>		
		<%= u.submit "Valider", class: "btn btn-lg btn-success btn-block"  %>
	<% end %>

</div>

app/views/operation_classifications/index.html.erb
<% content_for :jumbo do %>
	<h1 class="page-header">Liste de vos types d'opérations</h1>
<% end %>

<div class="row">

	<%= render partial: "layouts/error", locals: {errors: @oc.errors} %>

	<%= form_for @oc, :url => {:controller => "operation_classifications", :action => "add_operation_classification"}, html: {:class => "form-horizontal"} do |o| %>	
		<div class="form-group">		
			<%= label( "name", "Dénomination", class: "col-sm-3 control-label") %>
			<div class="col-sm-8">
				<%= o.text_field( :wording, class: "form-control", placeholder: "Nouveau poste",  required: true)%>
			</div>
		</div>
		<%= o.submit "Valider", class: "btn btn-lg btn-success btn-block"  %>
	<% end %>
	
	<br />
	
	<% @operationClassifications.each do |o| %>
	
		<div class="form-group">		
			<%= label "compte", o.wording, class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= link_to( "Modifier", edit_operation_classification_path(o), class: "btn btn-warning") %>
				<% if(o.operations.count == 0) %>					
					&nbsp;<%= link_to( "Supprimer", operation_classification_path(o), method: :delete, data: { confirm: "Supprimer l'opération ?" }, class: "btn btn-danger") %>
				<% end %>
			</div>
		
		</div>
		<br />
	<% end %>

</div>