config/routes.rb
Rails.application.routes.draw do	
	
	post 'bank_accounts/add_operation'
	get 'bank_accounts/delete_operation'
	
	post 'bank_accounts/define_date'
	
	post 'bank_accounts/update_operation'
	
	post 'operation_classifications/edit'
	post 'operation_classifications/update'
	post 'operation_classifications/add_operation_classification'
	
	get 'operations/check'
	get 'operations/uncheck'
	
	resources 	:bank_accounts, 
				:operations, 
				:users, 
				:operation_classifications,
				:transfers
	
	get 'home/login'
	post 'home/login'
	get 'home/index'
	get 'home/logout'

	get 'users/new'
	post 'users/create'
	
	get 'stats/evolution_solde'
	post 'stats/evolution_solde_data'
	get 'stats/operation_distribution'
	post 'stats/operation_distribution_data'
	get '/stats/evolution_poste'
	post '/stats/evolution_poste_data'
	post '/stats/input_output_data'
	
	

  root 'home#login'

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
	belongs_to :user,
		inverse_of: :bankAccounts
	
	belongs_to :devise
	belongs_to :bank_account_type
	has_many :operations
	has_many :transfers
	
	validates 	:name, :presence => { message: "Le nom du compte est obligatoire" }
	validates	:initial_amount, 
				:presence => { message: "Le montant initial est obligatoire" }, 
				:numericality => { message: "Le montant doit être numérique" }
	validates	:bank_account_type_id, presence: true
	validates	:devise_id, presence: true
	  
	def self.allByLoggedUser(idUser)
		User.find(idUser).bankAccounts.all
	end 
  
	def smart_final_amount()
		"#{final_amount} #{devise.symbol}"
	end 
	
	def current_final_amout()
	  #get all actives operations (0 == output, 1 == input)
	  to_return = final_amount + Operation.where(bank_account_id: id).where(movement: 0).where(operation_valid:'not_ok').sum(:amount)
	  to_return - Operation.where(bank_account_id: id).where(movement: 1).where(operation_valid:'not_ok').sum(:amount)
	end
	
	def addBankAccount(my_user_id)
		self.user_id = my_user_id
		rebuild_final_amount()
		save()
	end	
	
	def updateBankAccount()
		rebuild_final_amount()
		save()
	end	
	
	def self.addOperation(my_operation)
		my_operation.save
		if(my_operation.movement == 'input')
			my_operation.bank_account.final_amount += my_operation.amount
		else
			my_operation.bank_account.final_amount -= my_operation.amount
		end
		my_operation.bank_account.save()	
	end
	
	def self.removeOperation(operation_id)
		my_operation = Operation.find(operation_id)		
		if(my_operation.movement_type == 'transfer')
			removeTransferOperation(my_operation)
		else
			removeNormalOperation(my_operation)
		end			
	end
	
	def self.updateOperation(my_operation, op_params)
		if(my_operation.movement_type == 'transfer')
			updateTransferOperation(my_operation, op_params)
		else
			updateNormalOperation(my_operation, op_params)
		end			
	end
	
	def rebuild_final_amount()
		amount = self.initial_amount		
		amount = amount + self.operations.input.sum(:amount)		
		amount = amount - self.operations.output.sum(:amount)	
		self.final_amount = amount
	end	
	
	private 
		def self.removeNormalOperation(my_operation)
			updateBankAccountAmount(my_operation)
			my_operation.destroy
		end
		
		def self.removeTransferOperation(my_operation)
			my_transfer = Transfer.where("to_operation_id = ? or from_operation_id = ?", my_operation.id, my_operation.id).first
			removeNormalOperation(my_transfer.to_operation)
			removeNormalOperation(my_transfer.from_operation)
			my_transfer.destroy
		end
		
		def self.updateNormalOperation(my_operation, op_params)
			removeNormalOperation(my_operation)
			addOperation(Operation.new(
					bank_account_id: op_params[:bank_account_id], 
					date_operation: op_params[:date_operation], 
					wording: op_params[:wording], 
					operation_classification_id: op_params[:operation_classification_id], 
					amount: op_params[:amount], 
					movement: op_params[:movement], 
					movement_type: op_params[:movement_type]				
				))
		end
		
		def self.updateTransferOperation(my_operation, op_params)
			my_transfer = Transfer.where("to_operation_id = ? or from_operation_id = ?", my_operation.id, my_operation.id).first
			updateNormalOperation(my_transfer.to_operation, op_params)
			updateNormalOperation(my_transfer.from_operation, op_params)		
		end
		
		def self.updateBankAccountAmount(my_operation)
			if(my_operation.movement == 'input')
				my_operation.bank_account.final_amount -= my_operation.amount
			else
				my_operation.bank_account.final_amount += my_operation.amount
			end
			my_operation.bank_account.save()
		end
end

app/models/bank_account_type.rb
class BankAccountType < ActiveRecord::Base
	has_many :bank_account	
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController

	before_filter :check_if_logged
	skip_before_filter :verify_authenticity_token, :only => [:define_date]
	
	def show
		@bankAccount = BankAccount.find(params[:id])		
		
		if(check_if_user_own_bank_account(@bankAccount))
		
			if(session[:begin_date] == nil)
				session[:begin_date] = Date.today.beginning_of_month
			end
			
			if(session[:end_date] == nil)
				session[:end_date] = (Date.today >> 1).beginning_of_month			
			end
			return @bankAccount
		
		end
	end
	
	def index
		@bankAccount = BankAccount.allByLoggedUser(session[:current_user_id])
	end
	
	def new
		@bankAccount = BankAccount.new(account_owner: User.find(session[:current_user_id]).fullname)
	end
	
	def edit
		@bankAccount = BankAccount.find(params[:id])
		if(check_if_user_own_bank_account(@bankAccount))
			return @bankAccount
		end
	end
	
	def destroy
		@bankAccount = BankAccount.find(params[:id])
		if(check_if_user_own_bank_account(@bankAccount))
			@bankAccount.destroy		
			redirect_to action: 'index'	
		end
	end
	
	def update		
	 	@bankAccount = BankAccount.find(params[:id])
		if(check_if_user_own_bank_account(@bankAccount))
		
			if(@bankAccount.update(bankAccount_params))
				@bankAccount.updateBankAccount()
				redirect_to action: 'index'	
			else
				render 'edit'
			end
		
		end
	end
	
	def create		
		@bankAccount = BankAccount.new(bankAccount_params)
		if(@bankAccount.valid?)
			@bankAccount.addBankAccount(session[:current_user_id])	
			redirect_to action: 'index'		
		else			
			render 'new'
		end
	end	
	
	def add_operation
		#render plain: params[:operation].inspect
		@my_operation = Operation.new(operation_params)
		if(@my_operation.valid?)		
			BankAccount.addOperation(@my_operation)		
		end
		@bankAccount = BankAccount.find(@my_operation.bank_account_id)
		render 'show'
	end
	
	def delete_operation	
		if(check_if_user_own_operation(params[:id_operation]))
			BankAccount.removeOperation(params[:id_operation])		
			redirect_to action: 'show', :id => params[:id_bank_account]
		end
	end
	
	def update_operation
		if(check_if_user_own_operation(params[:operation][:id]))
			my_operation = Operation.find(params[:operation][:id])		
			BankAccount.updateOperation(my_operation, operation_params)
			redirect_to action: 'show', :id => my_operation.bank_account_id
		end
	end
	
	def define_date
		new_date = Date.new(params[:define_date_year].to_i, params[:define_date_month].to_i, 1)
		
		session[:begin_date] = new_date.beginning_of_month
		session[:end_date] = (new_date >> 1).beginning_of_month	
		@bankAccount = BankAccount.find(params[:id])
		render 'show'
	end
	
	private
		def bankAccount_params
			params.require(:bank_account).permit(:name, :initial_amount, :devise_id, :bank_account_type_id, :account_number, :account_owner)
		end
		
		def operation_params
			params.require(:operation).permit(:bank_account_id, :date_operation, :wording, :operation_classification_id, :amount, :movement, :movement_type)
		end
end

app/views/bank_accounts/_edit_operation.html.erb
<div class="modal fade" id="test_modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title">Modification d'une opération</h4>
			</div>
			<%= form_for @operation, html: {:class => "form-horizontal"}, :url => {:controller => "bank_accounts", :action => "update_operation"} do |o| %>
				<div class="modal-body">				
					
					<%= o.hidden_field( :id ) %>
					<%= o.hidden_field( :movement ) %>
					<%= o.hidden_field( :movement_type ) %>
					<%= o.hidden_field( :bank_account_id ) %>
					
					<div class="form-group">		
						<%= label "date_operation", "Date d'opération", class: "col-sm-4 control-label" %>
						<div class="col-sm-8">
							<%= o.date_field( :date_operation, class: "form-control", required: true  ) %>					
						</div>
					</div>
					
					<div class="form-group">
						<%= label "wording", "Libellé", class: "col-sm-4 control-label" %>
						<div class="col-sm-8">
							<%= o.text_field( :wording, class: "form-control", required: true ) %>				
						</div>
					</div>
					
					<% if(@operation.movement_type != "transfer") %>
					
					<div class="form-group">
						<%= label "operation_classification_id", "Poste", class: "col-sm-4 control-label" %>
						<div class="col-sm-8">
							<%= o.collection_select( :operation_classification_id, OperationClassification.all, :id, :wording, {}, { class: "form-control"} ) %>
						</div>
					</div>			
					
					<% end %>					
					
					<div class="form-group">
						<%= label "amount", "Montant", class: "col-sm-4 control-label" %>
						<div class="col-sm-8">
							<%= o.number_field( :amount, :step => 0.01, class: "form-control", required: true) %>
						</div>
					</div>				
					
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
					<button type="submit" class="btn btn-primary">Enregister</button>
				</div>
			<% end %>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>

<script>
	$(document).on("click", ".open_operation_dialog", function () {     
		 $(".modal-body #operation_id").val( $(this).data('id') );
		 $(".modal-body #operation_date_operation").val( $(this).data('date_operation') );
		 $(".modal-body #operation_wording").val( $(this).data('wording') );
		 $(".modal-body #operation_movement").val( $(this).data('movement') );
		 $(".modal-body #operation_amount").val( $(this).data('amount') );
		 $(".modal-body #operation_operation_classification_id").val( $(this).data('operation_classification_id') );		 
	});
</script>

app/views/bank_accounts/_form.html.erb
<div class="row">

	<%= render partial: "layouts/error", locals: {errors: @bankAccount.errors} %>

	<%= form_for @bankAccount, html: {:class => "form-horizontal"} do |b| %>	 
		<div class="form-group">		
			<%= label "name", "Dénomination", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= b.text_field( :name, class: "form-control", placeholder: "Nom du compte")%>
			</div>			
		</div>
		<div class="form-group">
			<%= label "account_number", "Numéro de compte", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= b.text_field( :account_number, class: "form-control", placeholder: "Numéro de compte")%>
			</div>
		</div>
		<div class="form-group">
			<%= label "account_owner", "Détenteur du compte", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= b.text_field( :account_owner, class: "form-control", placeholder: "Détenteur du compte")%>
			</div>
		</div>
		<div class="form-group">
			<%= label "initial_amount", "Montant initial", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= b.number_field( :initial_amount, :step => 0.01, class: "form-control", placeholder: "Montant initial") %>
			</div>
		</div>
		<div class="form-group">
			<%= label "bank_account_type_id", "Type de compte", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= b.collection_select( :bank_account_type_id, BankAccountType.all, :id, :wording, {}, {:class=>"form-control"}) %>
			</div>
		</div>
		<div class="form-group">
			<%= label "devise_id", "Devise", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= b.collection_select( :devise_id, Devise.all, :id, :wording, {}, {:class=>"form-control"}) %>
			</div>
		</div>	
		
		<%= b.submit "Valider", class: "btn btn-lg btn-success btn-block"  %>
	<% end %>
	
</div>

app/views/bank_accounts/_month_choise.html.erb
<% 
	@previous_month = ((session[:begin_date].to_date) << 1).month
	@previous_year = ((session[:begin_date].to_date) << 1).year
	@next_month = ((session[:begin_date].to_date) >> 1).month
	@next_year = ((session[:begin_date].to_date) >> 1).year
%>
<div class="col-md-2 text-right">
	<button class="btn btn-default" type="button" onclick="post('/bank_accounts/define_date',{define_date_month: <%= @previous_month %>,define_date_year: <%= @previous_year %> , id: '<%= @bankAccount.id %>'});">
		<i class="fa fa-arrow-circle-left"></i>&nbsp;Précédent</button>
</div>
<div class="col-md-4">
	<div class="form-group input-group" id="datepicker" 
			data-date="<%= (session[:begin_date].to_date).strftime("%m-%Y") %>" 
			data-date-format="mm-yyyy">		
		<input type="text" class="form-control" readonly="readonly" id="define_date" name="define_date" value="<%= (session[:begin_date].to_date).strftime("%m-%Y") %>" >
		<span class="input-group-btn">
			<button class="btn btn-default" type="button"><i class="fa fa-calendar"></i>
			</button>
		</span>	
	</div>
</div>
<div class="col-md-2">
	<button class="btn btn-default" type="button" onclick="post('/bank_accounts/define_date',{define_date_month: <%= @next_month %>,define_date_year: <%= @next_year %> , id: '<%= @bankAccount.id %>'});">
		Suivant&nbsp;<i class="fa fa-arrow-circle-right"></i></button>
</div>

app/views/bank_accounts/edit.html.erb
<% content_for :jumbo do %>
	<h1 class="page-header">Modification du compte</h1>
<% end %>

<%= render "form" %>

app/views/bank_accounts/index.html.erb
<% content_for :jumbo do %>
	<h1 class="page-header">Liste de vos comptes</h1>	
<% end %>

<div class="row">
	<div class="form-group">		
		<%= label "Ajouter un compte", "Ajouter un compte", class: "col-sm-3 control-label" %>
		<div class="col-sm-8">
			<%= link_to "Nouveau Compte", new_bank_account_path, class: "btn btn-primary" %>
		</div>			
	</div>
	<br /><hr /><br />
	<% @bankAccount.each do |b| %>
	
		<div class="form-group">		
			<%= label "compte",  b.name + " (" + b.smart_final_amount + ")", class: "col-sm-3 control-label" %>
			<div class="col-sm-8">
				<%= link_to "Modifier", edit_bank_account_path(b), class: "btn btn-warning" %>
				&nbsp;
				<%= link_to "Supprimer", bank_account_path(b), method: :delete, data: { confirm: "Supprimer le compte ?" }, class: "btn btn-danger" %>
			</div>			
		</div>
		<br /><br />
	<% end %>
		
</div>

app/views/bank_accounts/new.html.erb
<% content_for :jumbo do %>
	<h1 class="page-header">Nouveau compte</h1>
<% end %>

<%= render "form" %>
	

app/views/bank_accounts/show.html.erb
<% content_for :jumbo do %>
	<h1 class="page-header"><%= @bankAccount.name %> | 
		<%= I18n.l session[:begin_date].to_date, :format => "%B %Y" %>
	</h1>	
<% end %>

<div class="row">

	<div class="col-md-6">
		<div class="panel-body">
			<div class="flot-chart" style="height:70px;">
				<div class="flot-chart-content" id="flot-bar-chart" style="padding: 0px; position: relative;">
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<h3>Solde : <%= number_to_currency(@bankAccount.final_amount, unit: @bankAccount.devise.symbol, format: "%n %u") %></h3>
		<h5>Actuel : <%= number_to_currency(@bankAccount.current_final_amout(), unit: @bankAccount.devise.symbol, format: "%n %u")%></h5>
	</div>

</div>

<hr />

<div class="row">

<!-- month chose -->
<%= render "month_choise" %>
<!-- end month choise -->

<% @operation = Operation.new(bank_account_id: @bankAccount.id, movement_type: "normal") %>

<%= form_for @operation, :url => {:controller => "bank_accounts", :action => "add_operation"} do |o| %>
	<%= o.hidden_field ( :bank_account_id ) %>
	<%= o.hidden_field ( :movement_type ) %>
	<table>
		<table class="table">
			<thead>
				<tr>			
					<td colspan="2">Date</td>
					<td>Libell&eacute;</td>
					<td>Poste</td>
					<td></td>
					<td></td>
					<td colspan="2"></td>
					<td colspan="2"></td>
				</tr>
			</thead>
			<tbody>
			
				<tr>
					<td colspan="2"><%= o.date_field( :date_operation, :value => Date.today.to_s(:db), class: "form-control", required: true ) %></td>
					<td><%= o.text_field( :wording, class: "form-control", required: true ) %></td>
					<td><%= o.collection_select( :operation_classification_id, OperationClassification.where(user_id: session[:current_user_id]).order("wording"), :id, :wording, {}, { class: "form-control"} ) %></td>
					<td><%= o.select( :movement, options_for_select([["Débit", "output"], ["Crédit", "input"]]), {}, { class: "form-control"} ) %>
					<td colspan="2"><%= o.number_field( :amount, :step => 0.01, class: "form-control", placeholder: "Montant", required: true) %></td>				
					<td colspan="2"><%= o.submit "Ajouter", class: "btn btn-success"  %></td>
				</tr>
				<% @bankAccount.operations.where(
					'date_operation >= ?', session[:begin_date]).where(
					'date_operation < ?', session[:end_date]).order(:date_operation).order(:id).reverse_order.each do |o| %>
				<% if(o.movement == "input") %>
					<tr class="success">
				<% else %>
					<tr class="warning">
				<% end %>
					<td>
						<% if(o.movement_type == "transfer") %>
							<i class="fa fa-exchange"></i>
						<% end %>
					</td>
					<td><%= o.date_operation.strftime("%d/%m/%Y") %>
					<td><%= o.wording %></td>
					<td><%= o.operation_classification.wording %></td>
					
					<% if(o.movement == "input") %>
						<td><%= number_to_currency(o.amount, unit: @bankAccount.devise.symbol, format: "%n %u") %></td>
					<% else %>
						<td></td>
					<% end %>				
					<% if(o.movement == "output") %>
						<td><%= number_to_currency(o.amount, unit: @bankAccount.devise.symbol, format: "%n %u") %></td>
					<% else %>
						<td></td>
					<% end %>
					
					<% if(o.operation_valid == "not_ok") %>
					
						<% if(o.movement_type == "transfer") %>
							<td></td>
						<% else %>
							<td>
								<a href="#test_modal" 
									data-toggle="modal" 
									data-id="<%= o.id %>"
									data-date_operation="<%= o.date_operation.strftime("%Y-%m-%d") %>"
									data-operation_classification_id="<%= o.operation_classification_id %>"
									data-wording="<%= o.wording %>"
									data-movement="<%= o.movement %>"
									data-amount="<%= o.amount %>"
									class="open_operation_dialog btn btn-warning btn-xs">
								Modifier</a>
							</td>
						<% end %>
						<td>			
						<%= link_to "Supprimer",{:controller => "bank_accounts", :action => "delete_operation", :id_operation => o.id, :id_bank_account => @bankAccount.id }, 
							data: { confirm: "Supprimer l'opération ?" }, 
							class: "btn btn-danger btn-xs" %>
						</td>
						<td>
							<%= link_to "Clore", { :controller => "operations", :action => "check", :id => o.id, :id_bank_account => @bankAccount.id }, class: "btn btn-default btn-xs" %>
						</td>					
					<% else %>
						<td colspan="3">
							<%= link_to "Declore", { :controller => "operations", :action => "uncheck", :id => o.id, :id_bank_account => @bankAccount.id }, class: "btn btn-default btn-xs" %>
						</td>					
					<% end %>
					
				</tr>
			<% end %>
			</tbody>
		</table>	
	</table>

<% end %>

</div>

<%= render "edit_operation" %>

<script>
$("#datepicker").datepicker({
				viewMode: 'months',
				minViewMode: 'months',
				format: 'mm-yyyy'
		}).on("changeDate", function(e){				
			//console.log(e.date.getMonth() + 1);
			//console.log(e.date.getYear());
			post('/bank_accounts/define_date', {define_date_month: e.date.getMonth() + 1,define_date_year: e.date.getFullYear() , id: '<%= @bankAccount.id %>'});				
    });

function post(path, params, method) {
    method = method || "post"; // Set method to post by default if not specified.
    var form = document.createElement("form");
    form.setAttribute("method", method);
    form.setAttribute("action", path);

    for(var key in params) {
        if(params.hasOwnProperty(key)) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", params[key]);
            form.appendChild(hiddenField);
         }
    }

    document.body.appendChild(form);
    form.submit();
}

$(document).ready(function() {			
		loadChart();
	});
	
function loadChart(){	
		$.ajax({
			url: "/stats/input_output_data",
			data: 	{ 	
						month : '<%= session[:begin_date] %>',
						bank_account_id: <%= @bankAccount.id %>
					},
			type: "POST",
			format: "json"
		}).done(
			function(jsonData) {
				var data = [{data: [[jsonData.input,1]], color: "green"},             
						{data: [[jsonData.output,0]], color: "orange"}];				
				
				var ticks = [
						[1, "Revenus " + jsonData.input + " €"],
						[0, "Dépenses " + jsonData.output + " €"]
					];
				
				var options = {	
						series: {
							bars: {
								show: true
							}
						},
						bars: {
							align: "center",
							barWidth: 0.8,
							horizontal: true							
						},		
						yaxis: {		
							ticks: ticks,
							color: "black",
							tickColor: "#ffffff",
							axisLabelFontSizePixels: 12,
							axisLabelFontFamily: 'Verdana, Arial',
							axisLabelPadding: 3
						},
						xaxis: {   
							ticks: 0
						},
						grid: {							
							borderColor: {top: "#ffffff", left: "#ffffff"}
						}
					};					
				
				$.plot($("#flot-bar-chart"), data, options);				
			}
		).fail(
			function() {
				console.log( "error" );
				})
				
		};		
	
</script>