config/routes.rb
Rails.application.routes.draw do	
	
	post 'bank_accounts/add_operation'
	get 'bank_accounts/delete_operation'
	
	post 'bank_accounts/define_date'
	
	post 'bank_accounts/update_operation'
	
	post 'operation_classifications/edit'
	post 'operation_classifications/update'
	post 'operation_classifications/add_operation_classification'
	
	get 'operations/check'
	get 'operations/uncheck'
	
	resources 	:bank_accounts, 
				:operations, 
				:users, 
				:operation_classifications,
				:transfers
	
	get 'home/login'
	post 'home/login'
	get 'home/index'
	get 'home/logout'

	get 'users/new'
	post 'users/create'
	
	get 'stats/evolution_solde'
	post 'stats/evolution_solde_data'
	get 'stats/operation_distribution'
	post 'stats/operation_distribution_data'
	get '/stats/evolution_poste'
	post '/stats/evolution_poste_data'
	post '/stats/input_output_data'
	
	

  root 'home#login'

end

app/views/layouts/_error.html.erb
<% if errors.any? %>
	<div class="bg-danger error-msg">
		<h1><%= pluralize(errors.count, "erreur") %> dans le formulaire</h1>
			
		<% errors.messages.values.each do |msg| %>
			<%msg.each do  |m| %>
				<%= m %><br />
			<%end %>
		<% end %>
			
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DaGet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if session[:current_user_id] != nil %>

<div id="wrapper">

	<!-- Navigation -->
	
	<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/home/index">DaGet - budget en ligne</a>
		</div>
		<!-- /.navbar-header -->
		
		<ul class="nav navbar-top-links navbar-right">
			<!-- /.dropdown -->
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-user">
					<li><%= link_to( raw("<i class='fa fa-user fa-fw'></i> Mon profil"), edit_user_path(:id => session[:current_user_id]) )%></li>
					<li><%= link_to( raw("<i class='fa fa-credit-card fa-fw'></i> Mes types d'opérations"), operation_classifications_path )%></li>		
					<li><%= link_to( raw("<i class='fa fa-calculator fa-fw'></i> Mes comptes"), bank_accounts_path )%></li>											
					<li class="divider"></li>
					<li><a href="/home/logout"><i class="fa fa-sign-out fa-fw"></i> D&eacute;connexion</a></li>
				</ul>
				<!-- /.dropdown-user -->
			</li>
			<!-- /.dropdown -->
		</ul>
		<!-- /.navbar-top-links -->
		
		<div class="navbar-default sidebar" role="navigation">
			 <div class="sidebar-nav navbar-collapse">
				<ul class="nav" id="side-menu">			
					<li>
						<a href="#"><i class="fa fa-calculator fa-fw"></i> Comptes<span class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<% User.find(session[:current_user_id]).bankAccounts.all.order(:bank_account_type_id).order(:name).each do |b| %>		
								<li>
									<%= link_to(b.name , bank_account_path(b)) %>
								</li>
							<% end %>                                
						</ul>
						<!-- /.nav-second-level -->
					</li>
					<li>
						<%= link_to(raw("<i class='fa fa-exchange fa-fw'></i> Virements"), new_transfer_path) %>
					</li>
					<li>
						<a href="#"><i class="fa fa-bar-chart"></i> Statistiques<span class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<li>
								<%= link_to("Répartition par postes", "/stats/operation_distribution" ) %>
							</li>
							<li>
								<%= link_to("Evolution d'un poste", "/stats/evolution_poste") %>
							</li>
							<li>
								<%= link_to("Evolution du solde", "/stats/evolution_solde")%>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>	

	<div id="page-wrapper">
		<div class="row">
			<div class="col-lg-12">
				<%= yield :jumbo %>
			</div>
		<!-- /.col-lg-12 -->
		</div>
		<!-- /.row -->
		
		<%= yield %>
		
	</div>

</div>

<script>
	$('#side-menu').metisMenu();
</script>

<% else %>

	<%= yield %>
	
<% end %>

</body>
</html>